### ISSUE TITLE
create text file

### ISSUE THREAD

**Issue by callmekohei** [mattn/memo#22]
Thank you for your great works! 😄 

# summary
create text file

## now
create only markdown file

## expected
create favarite file type

## config file
```toml
createfiletype = 'txt'  # enable to create text file
listfiletype   = ' * '  # enable to list cmd for every file type
editfiletype   = ' * '  # enable to edit cmd for every file type
```
